export const GET_SMURFS_START = 'GET_SMURFS_START';
export const GET_SMURFS_FINISH = 'GET_SMURFS_FINISH';
export const GET_SMURFS_FAIL = 'GET_SMURFS_FAIL';

export const ADD_SMURFS_START = 'ADD_SMURFS_START';
export const ADD_SMURFS_FINISH = 'ADD_SMURFS_FINISH';
export const ADD_SMURFS_FAIL = 'ADD_SMURFS_FAIL';

export const UPDATE_SMURFS_START = 'UPDATE_SMURFS_START';
export const UPDATE_SMURFS_FINISH = 'UPDATE_SMURFS_FINISH';
export const UPDATE_SMURFS_FAIL = 'UPDATE_SMURFS_FAIL';

export const DELETE_SMURFS_START = 'DELETE_SMURFS_START';
export const DELETE_SMURFS_FINISH = 'DELETE_SMURFS_FINISH';
export const DELETE_SMURFS_FAIL = 'DELETE_SMURFS_FAIL';
